apiVersion: v1
kind: Service
metadata:
  name: globalmedicare-backend-service
spec:
  type: NodePort
  selector:
    app: globalmedicare-backend
  ports:
    - protocol: TCP
      port: 30084
      targetPort: 30084
      nodePort: 30084

